sudo: false
language: ruby
cache: bundler
rvm:
  - 2.6.6

install:
  # Install Jekyll and dependencies
  - bundle install

before_script:
  - git config --global user.email "joohyung1002@naver.com"
  - git config --global user.name "joo-pe"

script: bundle exec rake site:deploy --quiet #--trace

# Generate your secure token with the travis gem:
# get Github token from your Travis CI profile page
# gem install travis
# GH_TOKEN from https://github.com/settings/tokens
# travis encrypt 'GIT_NAME="YOUR_USERNAME" GIT_EMAIL="YOUR_EMAIL" GH_TOKEN=YOUR_TOKEN'
env:
  global:
    secure: "cI1CoZZhI965ieZm96+kJdHrLIq1HNhlHoxAPMpOduYB0tQfHToiNIW6lE8XOypXn3pBHtmwbXcINPaPF8KK+VPpm/Os9rX9Jo3yd7bZSRYx+lDio9ncUb6Ow7navW9aGcBNLPO4H+7FUxbCbniF3wuoJcV6qn9BLiIPFLjSXmN2/+3bTWBn5C2Z2beamjtwKCIfPhXfnhCY3L6rcniEpQ4vdceeZfYBcffK90rIo1SxsYlDyw0nMR28xzQExVfF3uWZgyC+6V2ns0xjpqfgEO+6LBhkUVvrpgerU9g9bTvnyBKdysCWlCBHJu967tjpWCnaDYY0XMDZEW8BysUu/wck8RCf+6NjGA9nGpKHQhumP+86rGCUCMdEU26wgsQpTf1EJ0XRzn5QXMpySPL469C/bS6nU0S5Bccxv/pYzp+DzJUlKuCDkFPCOZ/qHDyV8QhOBZAsxtQc8bS5kWGLsUVvkTv2++4RG+O49vtuEM0XIPhWZ3c7ct/itGCUgzA884dKsKc+LhuGckIEiNmTT/2EWj+s/p3ZhQlAZpahp4tjSuF4bny/xNyB1VlkUBCySz2V1A13sd0h6fqy5/XEmMNA/e5bTxBWkfoyCYQ8kCNmCgADZjFG9nkXRYPMIjdv0Nj2MfY6JT1pBuiSWwpx8hjhnIbiEPdSLJe2aHxbBRI="
branches:
  only:
    - master